### ISSUE TITLE
Designing and layout change of Project section.

### ISSUE THREAD

**Issue by Riddhi050803** [SnowScriptWinterOfCode/PortfolioCreations#10]
![Screenshot 2023-12-29 115346](https://github.com/SnowScriptWinterOfCode/PortfolioCreations/assets/122264483/d930f371-ede0-4d99-936b-afb8b58bd64a)
Wanted to change the designing and layout of the project section such that it looks similar to the above provided project section image in addition with the live website and github repo buttons.

**Comment by Riddhi050803** [comment]
Please assign this to me

**Comment by Riddhi050803** [comment]
PR #21 resolve this issue.

**Comment by ayushichoudhary-19** [comment]
This issue has been resolved by PR #21! 🎉
Closing as the changes have been successfully merged.
