### ISSUE TITLE
Revert Incorrect Changes

### ISSUE THREAD

**Issue by Pragya1601** [SnowScriptWinterOfCode/PortfolioCreations#103]
An incorrect pull request was recently merged, leading to unintended changes in the website's code. The merged code has resulted in an inappropriate appearance of the website. To address this issue, we need to revert the changes made in the erroneous pull request and restore the website to its previous state.

**Comment by ayushichoudhary-19** [comment]
Thanks for raising the issue! The PR has been rolled back, and everything on the website should be back to normal.
