### ISSUE TITLE
Website not Working 

### ISSUE THREAD

**Issue by priyagupta20044** [SnowScriptWinterOfCode/PortfolioCreations#104]
No section is in its correct page and nothing seems to work correctly. 
![image](https://github.com/SnowScriptWinterOfCode/PortfolioCreations/assets/121642923/f24ed645-71ce-4c18-8005-f572c1cfd791)

**Comment by ayushichoudhary-19** [comment]
The issue is now resolved, and everything is back to normal on the website.
