### ISSUE TITLE
Fix Homepage UI

### ISSUE THREAD

**Issue by Bluesparx** [SnowScriptWinterOfCode/PortfolioCreations#107]
### Issue Description
There is additional horizontal scroll which serves no purpose so needs to be removed. Also, Education section UI needs improvement, as it is not properly aligned for all devices. 

### Expected Behavior
Remove horizontal scroll and improve UI of education cards.

**Comment by Nitya-Pasrija** [comment]
Congratulations! Your first ever issue with us in this repository has been created. Please wait while it gets assigned to you.

**Comment by Bluesparx** [comment]
Please assign this to me @ayushichoudhary-19

**Comment by ayushichoudhary-19** [comment]
PR #109 Fixes the issue
