### ISSUE TITLE
Add a Better Pre-Loader Design

### ISSUE THREAD

**Issue by ayushichoudhary-19** [SnowScriptWinterOfCode/PortfolioCreations#110]
**Description:**
![image](https://github.com/SnowScriptWinterOfCode/PortfolioCreations/assets/73214455/b1280876-86e2-43c2-b966-179d9f591e76)
The current pre-loader on our website needs to align better with the design aesthetics, and we're looking for a universal loader that not only aligns seamlessly but also looks fantastic. We invite contributors to enhance the pre-loader to match the website's overall design better.

**Tasks:**
1. Investigate the current pre-loader design.
2. Propose a more universal pre-loader that aligns with the website's aesthetics.
3. Implement the new pre-loader design.
4. Test to ensure it works smoothly across different devices and browsers.
5. Submit a pull request with the changes.
6. Add a preview with the pull request.

**Additional Information:**
- Feel free to reach out for clarification or additional details.

We appreciate your contributions!

**Comment by PranjaliBhardwaj** [comment]
I can add a better reloader by using simple CSS. @ayushichoudhary-19

**Comment by ayushichoudhary-19** [comment]
Hi @PranjaliBhardwaj,  I've assigned the issue to you. Please submit a pull request within 48 hours. After that, it'll be open to other contributors.
