### ISSUE TITLE
Improve Certificate Section UI

### ISSUE THREAD

**Issue by ayushichoudhary-19** [SnowScriptWinterOfCode/PortfolioCreations#111]
**Description:**
The current certificate section displays an image carousel with three certificates on each slide, making it challenging for users to read due to their small size. The issue gets worse on mobile screens, where they become almost invisible.

**Expected Changes:**
1. Each slide should display a single certificate for improved visibility.
2. Ensure optimal size on all screen sizes.
3. Replace blank images with actual sample/arbitrary certificate images.
4. Align the color scheme with the website's design; eliminate the red currently used for navigators.

**UI Guidelines:**
A clean UI similar to the provided sample image is preferred. However, we welcome more creative designs. Please share your ideas in the comments below, and we'll assign the issue accordingly.

![image](https://github.com/SnowScriptWinterOfCode/PortfolioCreations/assets/73214455/983b2123-0d8d-4b19-82e5-fb57017807e5)

**Note:**
- Make sure to test the changes on various devices and screen sizes.
- Add a preview of your work in the Pull Request you create.

**Comment by ShaikArshidBanu** [comment]
@ayushichoudhary-19 please assign this issue to me.

**Comment by Aditi152004** [comment]
Please assign this issue to me.

**Comment by ayushichoudhary-19** [comment]
> @ayushichoudhary-19 please assign this issue to me.

Submit a pull request by tomorrow. After that, it will be open for other contributors.
