### ISSUE TITLE
Add logo

### ISSUE THREAD

**Issue by hars-21** [SnowScriptWinterOfCode/PortfolioCreations#118]
If required, logo/icon can be added on the tab.
the browser icon doesn't look good and not expected from a portfolio of web developer.

So, I'll be adding a icon it.
Icon provided below.
![businesswoman](https://github.com/SnowScriptWinterOfCode/PortfolioCreations/assets/144909381/392bc0c6-4014-4306-a4f6-3f9b471f0767)

**Comment by Prriya-Karn** [comment]
hi please assign this issue to me

**Comment by PranjaliBhardwaj** [comment]
Its easy and takes only one html tag, @ayushichoudhary-19 @Nitya-Pasrija can you assign this issue to me?

**Comment by hars-21** [comment]
Please assign this issue to me.
