### ISSUE TITLE
Adding a fixed side slider that includes all the social media links

### ISSUE THREAD

**Issue by Mahak008** [SnowScriptWinterOfCode/PortfolioCreations#12]
Like this 

![Screenshot (632)](https://github.com/SnowScriptWinterOfCode/PortfolioCreations/assets/88129955/87e35375-b649-4551-ba4a-82423de5b250)

Kindly assign this issue to me

**Comment by Nitya-Pasrija** [comment]
Woohoo! Your first ever issue with us in this repository has been created🎊🎊!!
