### ISSUE TITLE
Adding Functionality

### ISSUE THREAD

**Issue by hars-21** [SnowScriptWinterOfCode/PortfolioCreations#120]
Adding functionality to the contact me section.
Making contact icons clickable and functionable.

**Comment by Prriya-Karn** [comment]
@Harshil-Gupta21 please assign this issue to me.

**Comment by hars-21** [comment]
@Prriya-Karn Hey I am not the project admin. I am also a contributor and I don't have the permission to assign anyone, in fact i opened this issue to get me assigned

**Comment by Prriya-Karn** [comment]
> @Prriya-Karn Hey I am not the project admin. I am also a contributor and I don't have the permission to assign anyone, in fact i opened this issue to get me assigned

oh sorry

**Comment by hars-21** [comment]
@ayushichoudhary-19 Please assign me

**Comment by ayushichoudhary-19** [comment]
@Harshil-Gupta21 Submit the PR at the earliest.

**Comment by hars-21** [comment]
Will update by today
