### ISSUE TITLE
Add feedback section.

### ISSUE THREAD

**Issue by isakshiraj** [SnowScriptWinterOfCode/PortfolioCreations#122]
I want to add the feedback section in this format and use an Excel sheet to store all the feedback of the user.

feedback section:
<img width="481" alt="Screenshot 2024-01-16 193048" src="https://github.com/SnowScriptWinterOfCode/PortfolioCreations/assets/118617849/f4971644-ad19-4999-968a-396255a15f56">

Message will come after submitting:
<img width="510" alt="Screenshot 2024-01-16 193133" src="https://github.com/SnowScriptWinterOfCode/PortfolioCreations/assets/118617849/b4556316-94aa-4d45-9de1-5a0ecf082841">

Excel Sheet:
<img width="960" alt="Screenshot 2024-01-16 193343" src="https://github.com/SnowScriptWinterOfCode/PortfolioCreations/assets/118617849/6ba2ce99-af97-4519-bd9b-e17de4b462d4">

Please assign this issue to me.

**Comment by Nitya-Pasrija** [comment]
Congratulations! Your first ever issue with us in this repository has been created. Please wait while it gets assigned to you.

**Comment by isakshiraj** [comment]
Please assign this issue to me @Nitya-Pasrija

**Comment by Prriya-Karn** [comment]
please assign this issue to me

**Comment by ayushichoudhary-19** [comment]
@isakshiraj , assigned! Submit your PR within 48 hours.
