### ISSUE TITLE
CSS enhancement of Frequantly Asked Question section.

### ISSUE THREAD

**Issue by isakshiraj** [SnowScriptWinterOfCode/PortfolioCreations#123]
I want to enhance the CSS features of the Frequently Asked Question section in the following format.

![WhatsApp Image 2024-01-16 at 19 44 34_96317935](https://github.com/SnowScriptWinterOfCode/PortfolioCreations/assets/118617849/4d3a4199-38e1-4321-bcf8-970eeedeb359)
![WhatsApp Image 2024-01-16 at 19 44 34_46895dcd](https://github.com/SnowScriptWinterOfCode/PortfolioCreations/assets/118617849/7f3d91b3-3835-4240-809e-3d86c5329be6)

Please assign this issue to me.

**Comment by isakshiraj** [comment]
Please assign this issue to me @Nitya-Pasrija

**Comment by PranjaliBhardwaj** [comment]
@Nitya-Pasrija Can you  Assign this issue to me.
