### ISSUE TITLE
Improve Certificate Section UI

### ISSUE THREAD

**Issue by ayushichoudhary-19** [SnowScriptWinterOfCode/PortfolioCreations#128]
**Issue Description:**

**Current State:**
The current certificate section shares the same UI as the testimonials, leading to a lack of visual distinction between the two. Additionally, the current design displays text instead of images.

**Proposed Changes:**

1. **UI Differentiation:**
   - Redesign the certificate section to have a distinct and visually appealing UI that sets it apart from the testimonials.
   - Utilize a layout or styling elements that clearly distinguish certificates from testimonials, providing a more intuitive user experience.

2. **Add Sample Certificate Images:**
   - Incorporate actual sample certificate images to give users a realistic preview of how their certificates will be displayed.
   - Ensure that the images are of high quality and representative of typical certificates to enhance the visual appeal of this section.

3. **Responsiveness:**
   - Improve the responsiveness of the certificate section to ensure a seamless viewing experience across various devices, including desktops, tablets, and mobile phones.
   - Test the responsiveness thoroughly and make adjustments as needed to maintain readability and aesthetics on different screen sizes.

**Deadline:**
This issue is expected to be resolved within 48 hours of getting assigned to you.

**Comment by hars-21** [comment]
assign me please
