### ISSUE TITLE
add a download resume button on navbar

### ISSUE THREAD

**Issue by Mahak008** [SnowScriptWinterOfCode/PortfolioCreations#13]
Please assign this issue to me

**Comment by prathna17** [comment]
i really want to work on this issue. i have prior experience in web development

**Comment by Nitya-Pasrija** [comment]
Hey @prathna17 
I am assigning this issue to @Mahak008 for the moment, but you can choose to work together if that's alright with you both

**Comment by prathna17** [comment]
It's ok no issues
