### ISSUE TITLE
Fix the Website Preloader

### ISSUE THREAD

**Issue by ayushichoudhary-19** [SnowScriptWinterOfCode/PortfolioCreations#130]
### Issue Description:**

**Current State:**
The current website preloader is loading with a transparent background, revealing the existing content from the very start. This behavior diminishes the loading experience for users.

**Expected Behavior:**
   - Modify the preloader to have a white background, ensuring that the existing content is not visible until the preloader completes loading.

**Testing:**
   - Test the updated preloader on various browsers and devices to ensure consistent behavior.

**Deadline:**
The resolution of this issue is expected within 2 days of assignment.

**Comment by hars-21** [comment]
Assign me please

**Comment by ayushichoudhary-19** [comment]
@Harshil-Gupta21 Assigned
