### ISSUE TITLE
Enhance UI Consistency in Experience Section

### ISSUE THREAD

**Issue by ayushichoudhary-19** [SnowScriptWinterOfCode/PortfolioCreations#131]
### Issue Description:

**Current State:**
The UI of the Experience section does not align with the overall clean and consistent design of the rest of the website. Using different fonts, shadows, and font weights makes this section appear out of place.

**Issue Details:**

1. **Font Consistency:**
   - Fonts used in the Experience section are inconsistent with the rest of the website. 

2. **Shadow Effects:**
   - Shadows applied in the Experience section differ from the established shadow style in other sections, causing a visual inconsistency.

3. **Font Weights:**
   - The font weights utilized in the Experience section do not match the standardized weights across the website, creating a disjointed appearance.

**Enhancement Goals:**

1. **Harmonize Fonts:**
   - Standardize the font choices in the Experience section to align with the established font styles used throughout the website.

2. **Consistent Shadow Effects:**
   - Adjust shadows in the Experience section to match the style used consistently in other sections.

3. **Uniform Font Weights:**
   - Ensure that font weights in the Experience section adhere to the standardized weights applied across the website for a seamless look.

**Testing**
   - Test the changes across various browsers and devices to verify visual consistency.

**Deadline:**
The resolution of this issue is expected within 2 days of assignment.

**Comment by Anomasingh** [comment]
Please assign this issue to me..

**Comment by ayushichoudhary-19** [comment]
@Anomasingh assigned!
