### ISSUE TITLE
Make the About Us and Projects Section Responsive

### ISSUE THREAD

**Issue by ayushichoudhary-19** [SnowScriptWinterOfCode/PortfolioCreations#133]
### Issue Description

**Current State:**
The website lacks optimal responsiveness, resulting in specific issues that need attention for a better user experience.

**Issue Details:**

1. **Statistics Block Overlapping:**
   - On mobile devices, the blocks containing statistics in the About Us section are not responsive, causing overlap and hindering readability.

2. **Visibility of Project Buttons:**
   - The repo and demo buttons on project cards are not visible on mobile screens, impacting user interaction and accessibility.

**Enhancement Goals:**

1. **Responsive Statistics Block:**
   - Ensure that the blocks containing statistics in the About Us section respond appropriately to different screen sizes, avoiding overlap and maintaining readability.

2. **Visible Project Buttons:**
   - Enhance the visibility and accessibility of repo links and demo buttons on project cards for an improved mobile user experience.

**Testing:**
Test across various device sizes to ensure that the implemented changes enhance overall responsiveness without introducing new issues.

**Deadline:**
The resolution of this issue is expected within 2 days of assignment.

**Comment by Anomasingh** [comment]
Please Assign this issue to me...

**Comment by ayushichoudhary-19** [comment]
@Anomasingh Assigned!
