### ISSUE TITLE
Align Tech Stack Logos to Center on Top of Skill Names in Skills Section

### ISSUE THREAD

**Issue by ayushichoudhary-19** [SnowScriptWinterOfCode/PortfolioCreations#134]
### Issue Description:

**Current State:**
The tech stack logos in the Skills section are not aligned to the center on top of the skill names, causing a visual misalignment.
![image](https://github.com/SnowScriptWinterOfCode/PortfolioCreations/assets/73214455/172e8ac3-f39b-4ce2-97ae-17f2adb33150)

**Issue Details:**

1. **Logo Alignment Issue:**
   - The tech stack logos within the skill blocks are not centered on top of the respective skill names, affecting the overall visual presentation.

**Enhancement Goals:**

1. **Center Alignment:**
   - Adjust the layout to ensure the logos are aligned to the center on top of the corresponding skill names.

**Testing:**
Conduct testing across various browsers and devices to confirm that the implemented changes successfully align the logos to the centre.

**Deadline:**
The resolution of this issue is expected within 1 day of assignment.

**Comment by VenusCh001** [comment]
please assign this to me

**Comment by ayushichoudhary-19** [comment]
@VenusCh001 assigned!
