### ISSUE TITLE
Adding Dynamic scroll effects to Experience,testimonials,certificate,FAQs Sections

### ISSUE THREAD

**Issue by ShaikArshidBanu** [SnowScriptWinterOfCode/PortfolioCreations#135]
Proposed Dynamic scroll effect:

https://github.com/SnowScriptWinterOfCode/PortfolioCreations/assets/112767165/439cad20-a0c0-4b18-a48a-9800c2be3ce4

**Comment by ShaikArshidBanu** [comment]
@ayushichoudhary-19 please assign this issue to me.

**Comment by ayushichoudhary-19** [comment]
You can fix this under the issue #129 assigned to you. Closing this issue as duplicate.
