### ISSUE TITLE
Add experience section to the portfolio.

### ISSUE THREAD

**Issue by Mahak008** [SnowScriptWinterOfCode/PortfolioCreations#14]
Please assign this issue to me

**Comment by PranjaliBhardwaj** [comment]
I can add experience section to portfolio by matching UI and relevant sections and input areas. @Nitya-Pasrija pls assign this issue to me

**Comment by Mahak008** [comment]
Kindly assign this issue to me.

**Comment by Shubhra-Narang** [comment]
Please assign this issue to me!
