### ISSUE TITLE
Pre - Loader

### ISSUE THREAD

**Issue by Mahak008** [SnowScriptWinterOfCode/PortfolioCreations#15]
I would like to create an attractive pre loader before the appearance of actual website so as to give it an attractive look.

**Comment by Nitya-Pasrija** [comment]
Looking forward to this one

**Comment by Nitya-Pasrija** [comment]
Try to keep it unique and universal though

**Comment by ayushichoudhary-19** [comment]
@Mahak008, submit your Pull Request at the earliest. If we don't receive your submission soon, we may need to consider opening the issue for others to contribute.

**Comment by Pragya1601** [comment]
please assign this issue to me ...i will put a pre loader as coding ninja's 
website uses with a perfect quotation  on their website....so here I can put a tagline or related quotation .

**Comment by ayushichoudhary-19** [comment]
@Pragya1601, assigned!

**Comment by Mahak008** [comment]
> @Mahak008, submit your Pull Request at the earliest. If we don't receive your submission soon, we may need to consider opening the issue for others to contribute.

I have made the changes for which I have created a separate branch as well. Kindly review it.

**Comment by ayushichoudhary-19** [comment]
#85 Fixed the issue
