### ISSUE TITLE
use heading tag for important information or highlights the heading

### ISSUE THREAD

**Issue by Kalpana8055** [SnowScriptWinterOfCode/PortfolioCreations#16]
use bold and underline tag to highlights some text like experience,skils
![Heading-Tag-Hierarchy](https://github.com/SnowScriptWinterOfCode/PortfolioCreations/assets/154818080/ae3875f0-caef-415a-9bac-15aab58f10c9)

**Comment by muskanny** [comment]
@Kalpana8055 hey, can you please assign this to me?

**Comment by Kalpana8055** [comment]
@Nitya-Pasrija can you assign this to me

**Comment by PranjaliBhardwaj** [comment]
@Nitya-Pasrija I can add headings according to preference for respective heading tags. Kindly assign this issue to me

**Comment by Kalpana8055** [comment]
@ayushichoudhary-19 can you assign this to me
