### ISSUE TITLE
Issue_portfolio

### ISSUE THREAD

**Issue by Aditi152004** [SnowScriptWinterOfCode/PortfolioCreations#17]
Improving the colour contrast so to provide better user experience.

**Comment by Nitya-Pasrija** [comment]
Woohoo! Your first ever issue with us in this repository has been created🎊🎊!!

**Comment by ayushichoudhary-19** [comment]
@Aditi152004 , thank you for highlighting the need to improve color contrast for a better user experience. This is an important enhancement.

I'm assigning this issue to you. Please focus on adjusting the color contrast throughout the relevant components to ensure optimal readability and accessibility. Additionally, could you please share which color palette you plan to apply for these improvements? Your input will help ensure alignment with the overall design. Feel free to reach out if you have any questions or need further clarification. Looking forward to your improvements!

**Comment by ayushichoudhary-19** [comment]
Closing this issue under 'lacking-clarity'
