### ISSUE TITLE
Add resume section

### ISSUE THREAD

**Issue by navyasaini** [SnowScriptWinterOfCode/PortfolioCreations#18]
I would like to add the resume in the following format.
![image](https://github.com/SnowScriptWinterOfCode/PortfolioCreations/assets/120239936/08b2271e-a74c-4601-ac35-3ffeb955c8c6)
please assign this issue to me.

**Comment by Nitya-Pasrija** [comment]
Woohoo! Your first ever issue with us in this repository has been created🎊🎊!!

**Comment by navyasaini** [comment]
Please assign this issue to me. I would love to get started on it! @Nitya-Pasrija

**Comment by priyagupta20044** [comment]
Please assign this issue to me! I would like to add this section and make the website look good !!
