### ISSUE TITLE
Want to work on the project section

### ISSUE THREAD

**Issue by anjali-2904** [SnowScriptWinterOfCode/PortfolioCreations#19]
want to align the project section data  in the form a table so that it will look nice and become more readable for others.

![image](https://github.com/SnowScriptWinterOfCode/PortfolioCreations/assets/92749087/41d737b1-3811-4b36-8a7c-6a63da3bae9d)

**Comment by Nitya-Pasrija** [comment]
Woohoo! Your first ever issue with us in this repository has been created🎊🎊!!

**Comment by anjali-2904** [comment]
@ayushichoudhary-19 @Nitya-Pasrija  @i-am-SnehaChauhan
I really want to work on this section please assign this issue to me

**Comment by anjali-2904** [comment]
@Nitya-Pasrija @ayushichoudhary-19 @i-am-SnehaChauhan
can you please confirm

**Comment by ayushichoudhary-19** [comment]
@anjali-2904, thank you for your suggestion! An issue for changing the project section's layout already exists, and we currently have someone working on it.

If you have any more suggestions or ideas for this section's layout/design, let's continue the discussion on the existing issue #10 . Your input is valuable, and we appreciate your engagement!

**Comment by iaayushmaan** [comment]
@anjali-2904 Please ensure you review existing issues before creating a new one to avoid duplicity. Conducting this check each time is essential to prevent redundancy.
