### ISSUE TITLE
Create and Design Responsive Navbar

### ISSUE THREAD

**Issue by i-am-SnehaChauhan** [SnowScriptWinterOfCode/PortfolioCreations#2]
## Description
We need to implement a responsive navigation bar (navbar) for our website to ensure optimal user experience across different devices and screen sizes.

### Context
- **Current Behavior:**
  We currently do not have a navigation bar, or the existing one is not responsive.

- **Expected Behavior:**
  We aim to create a visually appealing and responsive navbar that adapts to various screen sizes, providing an optimal user experience on both desktop and mobile devices.

### Requirements
1. **Layout Design:**
   - Design a clean and intuitive navbar layout that includes menu items, a logo, and potentially a search bar.
   
2. **Styling:**
   - Apply consistent and aesthetically pleasing styling to the navbar, considering color schemes, typography, and any relevant branding guidelines.

3. **Responsiveness:**
   - Ensure the navbar is responsive and adjusts gracefully for different screen sizes (desktop, tablet, mobile).
   - Implement a mobile-friendly hamburger menu for smaller screens.
   
4. **Accessibility:**
   - Ensure the navbar is accessible, including keyboard navigation and screen reader compatibility.

### Screenshots 
![image](https://github.com/SnowScriptWinterOfCode/PortfolioCreations/assets/94298791/16885292-59cd-48eb-addf-c493b6b60918)
![image](https://github.com/SnowScriptWinterOfCode/PortfolioCreations/assets/94298791/23edabf3-9482-4c4b-a69e-cc6855b5ba50)

### Additional Information
Consider researching and incorporating best practices for responsive design and navigation bar implementation.

**Comment by Nitya-Pasrija** [comment]
Woohoo! Your first ever issue with us in this repository has been created🎊🎊!!

**Comment by Akanksha-202** [comment]
Hey! Would like to take upon the issue. Was thinking of implementing something like this:
![image](https://github.com/SnowScriptWinterOfCode/PortfolioCreations/assets/100708686/7a513b2d-35ef-4797-a41d-e23d74230299)
It will be responsive as well. For mobile screens, I can add a hamburger instead of the whole navbar too.
I will be using the Bootstrap framework to implement the idea.
Would love to work on issue.

**Comment by aarushisingh2004** [comment]
I'm interested in addressing this issue regarding the implementation of a responsive navbar. I have experience in doing this using css and can ensure a visually appealing and user-friendly design that adapts well to different devices.

Can this task be assigned to me? I'm excited to contribute to the project and will provide regular updates on my progress.

Thanks

**Comment by i-am-SnehaChauhan** [comment]
Hey @Akanksha-202, I am assigning this issue to u. You have two days to complete it, and then I have to assign it to someone else.

You can include Hamburger for mobile view only.

**Comment by ayushichoudhary-19** [comment]
This issue has been resolved by PR #22. Closing as the changes have been successfully merged.
