### ISSUE TITLE
Adding Education Section

### ISSUE THREAD

**Issue by MonalikaPatnaik** [SnowScriptWinterOfCode/PortfolioCreations#23]
I want to add the education section in Portfolio. Refer to this sample screenshot
![image](https://github.com/SnowScriptWinterOfCode/PortfolioCreations/assets/99353300/ce974dac-0e9d-4c42-8dc3-3d91d867596c)

**Comment by Nitya-Pasrija** [comment]
Woohoo! Your first ever issue with us in this repository has been created🎊🎊!!

**Comment by MonalikaPatnaik** [comment]
@i-am-SnehaChauhan assign me this issue

**Comment by i-am-SnehaChauhan** [comment]
Hey @MonalikaPatnaik, I am assigning this to u.
