### ISSUE TITLE
Adding a Scroll to Top Button

### ISSUE THREAD

**Issue by MonalikaPatnaik** [SnowScriptWinterOfCode/PortfolioCreations#24]
Hello, I want to add a scroll to top button in the website enhancing user experience and improved navigation. 
Sample ss-
![image](https://github.com/SnowScriptWinterOfCode/PortfolioCreations/assets/99353300/29b38e1f-eac9-4334-9acb-14c0a06c0391)

**Comment by PranjaliBhardwaj** [comment]
@Nitya-Pasrija I can add scroll button using html css and js.

**Comment by MonalikaPatnaik** [comment]
[@i-am-SnehaChauhan](https://github.com/i-am-SnehaChauhan) assign me this issue
