### ISSUE TITLE
Adding elements and adjusting the Landing Screen

### ISSUE THREAD

**Issue by Akanksha-202** [SnowScriptWinterOfCode/PortfolioCreations#3]
There is no image or description on the Landing Screen. Below is a preview of how we can add an image and a small and crisp introduction.
![image](https://github.com/SnowScriptWinterOfCode/PortfolioCreations/assets/100708686/2182ba14-9100-412c-ac0f-8b3c42776ca1)
This is just a preview, the actual implementation will be color-coordinated.

**Comment by Nitya-Pasrija** [comment]
Woohoo! Your first ever issue with us in this repository has been created🎊🎊!!

**Comment by prathna17** [comment]
I really wanted to work on this project. I have a prior experience in making a portfolio website
