### ISSUE TITLE
Adding Certificates Section

### ISSUE THREAD

**Issue by priyagupta20044** [SnowScriptWinterOfCode/PortfolioCreations#32]
I would like to add a certificate section with a scroll gallery like this, please assign this to me
![Screenshot 2023-12-31 204736](https://github.com/SnowScriptWinterOfCode/PortfolioCreations/assets/121642923/f5b7ed56-995a-4b0f-bca4-34020c429f85)

https://github.com/SnowScriptWinterOfCode/PortfolioCreations/assets/121642923/133a5fba-37e4-43bf-a265-a189a8fcb603

**Comment by Nitya-Pasrija** [comment]
Congratulations! Your first ever issue with us in this repository has been created. Please wait while it gets assigned to you.

**Comment by Nitya-Pasrija** [comment]
Assigned it to you @priyagupta20044 
Please start the work on it :) Also, do use the command git pull, to sync up recent changes while you work on it.
