### ISSUE TITLE
 Enhance Education Section with Dynamic Scroll Appearance

### ISSUE THREAD

**Issue by ayushichoudhary-19** [SnowScriptWinterOfCode/PortfolioCreations#39]
### Issue Description
Currently, the education section displays each entry in a static manner with alternating divs on the left and right. To enhance the user experience and create a dynamic effect, implement a scrolling animation that reveals each education entry one by one as the user scrolls down.

### Key Points:

1. Implement a scrolling animation for the education section to make the entries appear dynamically.
2. Preferred animation: a smooth slide-in effect from the sides for each entry.
3. Test the responsiveness and compatibility of the scrolling effect on various devices and browsers.

**Comment by Nitya-Pasrija** [comment]
Congratulations! Your first ever issue with us in this repository has been created. Please wait while it gets assigned to you.

**Comment by ShaikArshidBanu** [comment]
@ayushichoudhary-19 @Nitya-Pasrija I would like to work on this please assign this issue to me.

**Comment by ayushichoudhary-19** [comment]
@ShaikArshidBanu, assigned!
