### ISSUE TITLE
Styling the "Contact Me" Section

### ISSUE THREAD

**Issue by Akanksha-202** [SnowScriptWinterOfCode/PortfolioCreations#4]
The Contact Me section and footer will be merged and will be much enhanced in visual appearance along with all the icons and hover effects.

**Comment by Prachi402j** [comment]
Hey! I would like to take this issue. I was thinking about implementing a similar section showed in the following screenshot.
(
![contact me section prototype](https://github.com/SnowScriptWinterOfCode/PortfolioCreations/assets/145839278/dc65b3e1-c18c-44c0-9fd9-2741f74ced0d)
Adding a comment section and various social media handles)

**Comment by Konikakonika** [comment]
hey , kindly assign me this issue i m thinking because i have worked on that in webd bootcamp. https://github.com/Konikakonika/portfoliowebsite this is my portfolio website

**Comment by navyasaini** [comment]
Hey, I would like to improve the contact section and add one more aspect to it i.e. message and a submit button. 
![image](https://github.com/SnowScriptWinterOfCode/PortfolioCreations/assets/120239936/b537e929-f651-46d9-a846-da276c3d6dde)
Please assign this issue to me. I would love to work on it. @i-am-SnehaChauhan @Nitya-Pasrija

**Comment by ayushichoudhary-19** [comment]
@Akanksha-202 Still working on this issue? Please submit your PR by midnight or it'll be assigned to someone else.

**Comment by Akanksha-202** [comment]
> @Akanksha-202 Still working on this issue? Please submit your PR by midnight or it'll be assigned to someone else.

I was also assigned one more issue, I'll submit that one in a while and this I'll submit by tomorrow, please extend the timeline till tomorrow l, thankyou!

**Comment by Ankitmohanty2** [comment]
is this issue solved?? or shall i do?? if u assign to me??

**Comment by Akanksha-202** [comment]
Hey @Ankitmohanty2 !, I have worked over it now, and about to make a PR

**Comment by Pragya1601** [comment]
please assign the issue to me ..i will add all possible contacts  info on this.

**Comment by Akanksha-202** [comment]
The PR has been merged, they'll soon close this issue
