### ISSUE TITLE
 Enhance Education Section Design Consistency and Resize Cards

### ISSUE THREAD

**Issue by ayushichoudhary-19** [SnowScriptWinterOfCode/PortfolioCreations#40]
**Issue Description**:

The current design of the education section, positioned between the skills and projects sections, does not align with the card-like design used in both the skills and projects sections, where a box-shadow effect is applied.

**Proposed Changes**:

1. **Background Color**: Change the background color of the education section from white to match the consistent color theme used throughout the website for background.

2. **Card-like Appearance**: Modify the divs used for the education entries to have a card-like appearance. This involves creating a white-colored box with a box-shadow effect to maintain a cohesive design with the skills and projects sections.

3. **Resize Education Cards**: Reduce the size of the education cards to make them more visually balanced and in line with the overall design.

**Key Points**:

- Ensure that the new design aligns with the overall aesthetic of the website.
- Test the changes for responsiveness across different devices.

**Comment by aarushisingh2004** [comment]
please assign this issue to me

**Comment by ayushichoudhary-19** [comment]
@aarushisingh2004, thank you for taking on this task! Before you begin, please make sure to git pull the repository to sync with the latest changes. Additionally, as you work on the proposed design enhancements for the education section, please address any responsiveness issues in the experience section as well.

This issue is now assigned to you. Best of luck with the updates, and feel free to reach out if you have any questions or need further assistance!

**Comment by aarushisingh2004** [comment]
@ayushichoudhary-19 can u plz  help me with finding what all css is used in education section as their are no comments to tell where the education section section starting or ending in css

**Comment by ayushichoudhary-19** [comment]
@aarushisingh2004  submit your Pull Request at the earliest. If we don't receive your submission soon, we may need to consider opening the issue for others to contribute.

**Comment by ayushichoudhary-19** [comment]
@aarushisingh2004, I've added comments to the CSS for the education section in the latest styles.css file. Hope this helps! Please submit your Pull Request at the earliest. Your efforts are appreciated!

**Comment by aarushisingh2004** [comment]
@ayushichoudhary-19 ok thank u , working on it

**Comment by ayushichoudhary-19** [comment]
#Fixed in PR: #109
