### ISSUE TITLE
Enhancing footer, adding Quick links and social media icons to it.

### ISSUE THREAD

**Issue by Riddhi050803** [SnowScriptWinterOfCode/PortfolioCreations#43]
### Issue Description
Wanted to add Quick links, social media icons (links) and enhance the footer.

### Expected Behavior
I want to make it like this one.
![image](https://github.com/SnowScriptWinterOfCode/PortfolioCreations/assets/122264483/f85f2399-2850-4c94-aa14-43648d633d27)

### Actual Behavior
![image](https://github.com/SnowScriptWinterOfCode/PortfolioCreations/assets/122264483/26cd464a-23c3-47d7-942a-fd13657758ba)

**Comment by Riddhi050803** [comment]
Really wanted to do this. Please assign to me @Nitya-Pasrija  @ayushichoudhary-19

**Comment by ayushichoudhary-19** [comment]
@Riddhi050803 Go ahead. It's assigned to you
