### ISSUE TITLE
Smooth Hover effect

### ISSUE THREAD

**Issue by MonalikaPatnaik** [SnowScriptWinterOfCode/PortfolioCreations#45]
I want to add a smooth hover effect on the Projects section. Currently, the hover effects are quite quick and not looking good.
![image](https://github.com/SnowScriptWinterOfCode/PortfolioCreations/assets/99353300/2b010c15-7b19-41af-aa9c-95629dd9b75b)

**Comment by priyagupta20044** [comment]
please assign this to me

**Comment by ayushichoudhary-19** [comment]
@MonalikaPatnaik, assigned!
