### ISSUE TITLE
[FEAT]:Adding Google Map in the contact section.

### ISSUE THREAD

**Issue by ShaikArshidBanu** [SnowScriptWinterOfCode/PortfolioCreations#50]
Adding a map in the contact section.

![Screenshot 2024-01-04 001702](https://github.com/SnowScriptWinterOfCode/PortfolioCreations/assets/112767165/b2a5941b-b6a0-44c5-8978-aba072ec670b)

**Comment by Nitya-Pasrija** [comment]
Congratulations! Your first ever issue with us in this repository has been created. Please wait while it gets assigned to you.

**Comment by ShaikArshidBanu** [comment]
@Nitya-Pasrija @ayushichoudhary-19 assign this issue to me

**Comment by ayushichoudhary-19** [comment]
@ShaikArshidBanu, thank you for your suggestion. After careful consideration, we don't see the necessity or added value in implementing this change.
