### ISSUE TITLE
Enhance project section (Resize cards)

### ISSUE THREAD

**Issue by Tech-neophyte** [SnowScriptWinterOfCode/PortfolioCreations#58]
### Issue Description
The sizes of 3rd and 4th cards do not match the rest.. 

### Proposed Changes:
Resize Project Cards: Adjust the size of the project cards to ensure they are visually balanced and aligned with the overall section.

**Comment by ayushichoudhary-19** [comment]
@Tech-neophyte, kindly raise a PR to address the issue at the earliest before it's open for other contributors.
