### ISSUE TITLE
Adding Hover effects to the testimonals-cards

### ISSUE THREAD

**Issue by ShaikArshidBanu** [SnowScriptWinterOfCode/PortfolioCreations#61]
testimonal cards appearance can be improved by adding hover effect to it.

**Comment by ShaikArshidBanu** [comment]
@ayushichoudhary-19 @Nitya-Pasrija please assign this issue to me

**Comment by priyagupta20044** [comment]
@ayushichoudhary-19  please assign this to me! I really want to work on this
