### ISSUE TITLE
Hover effect and color change of Social media Icons

### ISSUE THREAD

**Issue by Malvika042** [SnowScriptWinterOfCode/PortfolioCreations#63]
### Screenshots (if relevant)

![WhatsApp Image 2024-01-05 at 3 53 33 PM](https://github.com/SnowScriptWinterOfCode/PortfolioCreations/assets/101415369/309ec5a1-2b03-4849-8ea3-5907e552524a)

### Additional Context

⚠️ **Warning**: Before submitting, please check for existing issues to avoid duplicates. If you find a related issue, consider adding your insights or upvoting the existing one. Thank you!

**Comment by Nitya-Pasrija** [comment]
Congratulations! Your first ever issue with us in this repository has been created. Please wait while it gets assigned to you.

**Comment by vidhiwalia** [comment]
please assign this issue to me @Nitya-Pasrija

**Comment by Malvika042** [comment]
> Congratulations! Your first ever issue with us in this repository has been created. Please wait while it gets assigned to you.

Done changes
