### ISSUE TITLE
Contact Form which link with the google sheets

### ISSUE THREAD

**Issue by Malvika042** [SnowScriptWinterOfCode/PortfolioCreations#64]
### Screenshots (if relevant)

![WhatsApp Image 2024-01-05 at 4 02 08 PM](https://github.com/SnowScriptWinterOfCode/PortfolioCreations/assets/101415369/f536dd1a-700d-43cc-82c3-363fe0b0539c)

⚠️ **Warning**: Before submitting, please check for existing issues to avoid duplicates. If you find a related issue, consider adding your insights or upvoting the existing one. Thank you!

**Comment by ayushichoudhary-19** [comment]
@Malvika042 Do you wish to work on this issue?

**Comment by Malvika042** [comment]
Yes

**Comment by Malvika042** [comment]
@ayushichoudhary-19  Can you please provide a Google Sheet link?
(where responses will be collected)

**Comment by Malvika042** [comment]
@Nitya-Pasrija @ayushichoudhary-19  can I add my Google sheet link?

**Comment by ayushichoudhary-19** [comment]
@Malvika042 You can add a Google Sheet link of your own, for now.

**Comment by ayushichoudhary-19** [comment]
@Malvika042, please submit a pull request at the earliest. Otherwise, the issue will be open for other contributors to take on.

**Comment by Malvika042** [comment]
Hi,

I wanted to let you know that I will be submitting the pull request soon
for the issue mentioned. I apologize for the delay and assure you that I
will take care of it as soon as possible.

Best regards,
Malvika

**Comment by ayushichoudhary-19** [comment]
@Malvika042, Make sure you git pull the latest repository before submitting the pull request in order to avoid any merge conflicts.
