### ISSUE TITLE
To Make Website Responsive

### ISSUE THREAD

**Issue by vidhiwalia** [SnowScriptWinterOfCode/PortfolioCreations#67]
### Additional Context

⚠️ **Warning**: Before submitting, please check for existing issues to avoid duplicates. If you find a related issue, consider adding your insights or upvoting the existing one. Thank you!

**Comment by Nitya-Pasrija** [comment]
Congratulations! Your first ever issue with us in this repository has been created. Please wait while it gets assigned to you.

**Comment by ayushichoudhary-19** [comment]
@vidhiwalia, kindly raise a PR to address the issue soon before it's open for other contributors.
