### ISSUE TITLE
Enhance About me section and navbar

### ISSUE THREAD

**Issue by hars-21** [SnowScriptWinterOfCode/PortfolioCreations#69]
1. Making navbar fixed so that user can quickly navigate through different sections.

2. Improving About Me section - UI enhancement and some fixes - To make attractive so that user can interested in reading full description.

**Comment by Nitya-Pasrija** [comment]
Congratulations! Your first ever issue with us in this repository has been created. Please wait while it gets assigned to you.

**Comment by hars-21** [comment]
Please assign this issue to me.

**Comment by ayushichoudhary-19** [comment]
@Harshil-Gupta21, feel free to proceed. This issue has been assigned to you.

**Comment by hars-21** [comment]
@ayushichoudhary-19 I have made a PR #98  for the issue #79 and in that PR this issue has also been resolved and About Me Section have been updated successfully. The UI enhancement have been achieved. Please review it.
