### ISSUE TITLE
Adding "Certificate" option in the navbar

### ISSUE THREAD

**Issue by priyagupta20044** [SnowScriptWinterOfCode/PortfolioCreations#70]
![image](https://github.com/SnowScriptWinterOfCode/PortfolioCreations/assets/121642923/e43239ee-2d5d-4204-8be4-95059bcaae43)

There is no option linked to certificate section, I would like to add it here, please assign me this  @ayushichoudhary-19

**Comment by Nehagarg816** [comment]
I want to do it..

**Comment by Nehagarg816** [comment]
![image](https://github.com/SnowScriptWinterOfCode/PortfolioCreations/assets/111566521/7c6c92da-f8b3-416a-9559-8cb6f43168a3)
I will transform it to this..
