### ISSUE TITLE
Add certification buttons - with links

### ISSUE THREAD

**Issue by namitabagri** [SnowScriptWinterOfCode/PortfolioCreations#8]
**Purpose** : To add a certifications section 

**Why is it useful** : Recruiters can press the buttons and have a look at the certifications that will open up in a new tab - like udemy certificates or any other licenses from google cloud, azure cloud etc.

**What will it look like** :  
(The color palette can be modified to go with the color of the rest of the page)
<img width="959" alt="image" src="https://github.com/SnowScriptWinterOfCode/PortfolioCreations/assets/46557775/6d91becf-68b9-4940-9693-d619b8f40df7">

**Comment by Nitya-Pasrija** [comment]
Woohoo! Your first ever issue with us in this repository has been created🎊🎊!!

**Comment by namitabagri** [comment]
@Nitya-Pasrija Can you please assign this issue to me

**Comment by ayushichoudhary-19** [comment]
No timely resolution of this issue, and in the meantime, another contributor has submitted a PR to add a certificate section. As a result, we're closing this issue.
