### ISSUE TITLE
project section enhancement

### ISSUE THREAD

**Issue by VenusCh001** [SnowScriptWinterOfCode/PortfolioCreations#81]
### Issue Description
currently the "projects" heading is at the left most part of the website which is not aligned well with the project section below the heading.

### Expected Behavior
bringing project heading at the Centre 

### Actual Behavior
project heading is left aligned

### Screenshots (if relevant)
![image](https://github.com/SnowScriptWinterOfCode/PortfolioCreations/assets/122210300/f7509493-9929-474b-bec5-7d20d693fbaf)

kindly assign

**Comment by Nitya-Pasrija** [comment]
Congratulations! Your first ever issue with us in this repository has been created. Please wait while it gets assigned to you.

**Comment by ayushichoudhary-19** [comment]
Hello, @VenusCh001! All the existing headings are a bit messy, with some centered and others left-aligned. If you're up for fixing not just the project section heading but all of them, I'll assign this issue to you right away.

**Comment by VenusCh001** [comment]
Okay 
I will align the project,experience,certificate section all of them @ayushichoudhary-19
