### ISSUE TITLE
contact section 

### ISSUE THREAD

**Issue by VenusCh001** [SnowScriptWinterOfCode/PortfolioCreations#82]
### Issue Description
contact section is having duplicacy as contact me section is present in main website also as well as footer

### Expected Behavior
removing the contact me section completely and footer contact section persists

### Actual Behavior
two contact sections are present one in the main website and other in the footer 

### Screenshots (if relevant)
![image](https://github.com/SnowScriptWinterOfCode/PortfolioCreations/assets/122210300/a2a417f8-05bd-4dfb-a690-c8050c520321)

**Comment by preetijangra15** [comment]
please assign this issue to me.

**Comment by ayushichoudhary-19** [comment]
@VenusCh001, please `git pull` the latest repository. The project already has a well-integrated 'Contact Me+Footer' section, addressing the concerns raised in this issue.
