### ISSUE TITLE
Adding hover effect to the testimonial section 

### ISSUE THREAD

**Issue by priyagupta20044** [SnowScriptWinterOfCode/PortfolioCreations#84]
Currently, the testimonial section has static cards, I want to add hover effects to it. 
Please assign this to me, @ayushichoudhary-19

**Comment by preetijangra15** [comment]
please assign this to me.

**Comment by ayushichoudhary-19** [comment]
@priyagupta20044 This is a duplicate issue, and another contributor is already working on a fix. If you have additional insights or details to add, feel free to contribute to the existing discussion.  #61
