### ISSUE TITLE
Add functionality to Download Resume Button.

### ISSUE THREAD

**Issue by Mahak008** [SnowScriptWinterOfCode/PortfolioCreations#87]
### Issue Description

On clicking download resume button, the resume of the candidate will be downloaded since as of now it doesn't do anything.

### Additional Context

⚠️ **Warning**: Before submitting, please check for existing issues to avoid duplicates. If you find a related issue, consider adding your insights or upvoting the existing one. Thank you!

**Comment by bj-jiwrajka** [comment]
@ayushichoudhary-19 kindly assign it to me:)

**Comment by bj-jiwrajka** [comment]
> @ayushichoudhary-19 kindly assign it to me:)

instead of downloading resume, it should redirect it to the drive link of the person's resume, I would just like to replace the option of "Download" and add ```target=_blank``` to open it in another tab, can I do that? @ayushichoudhary-19
