### ISSUE TITLE
Improve the UI of education section.

### ISSUE THREAD

**Issue by Mahak008** [SnowScriptWinterOfCode/PortfolioCreations#89]
### Issue Description

Education section is not aligned properly neither for laptop view nor for mobile view.

### Actual Behavior

![image](https://github.com/SnowScriptWinterOfCode/PortfolioCreations/assets/88129955/3d7c2b98-7db5-4fed-bfc9-4116ea378f78)
![Screenshot (639)](https://github.com/SnowScriptWinterOfCode/PortfolioCreations/assets/88129955/368c0ded-5239-4f7e-937c-f8dd95a3300f)

### Steps to Reproduce

I would like to change the UI a bit and make this section responsive.

### Additional Context

⚠️ **Warning**: Before submitting, please check for existing issues to avoid duplicates. If you find a related issue, consider adding your insights or upvoting the existing one. Thank you!

**Comment by ayushichoudhary-19** [comment]
Hello @Mahak008. The issue template is provided to ensure we gather detailed information on the issue/proposed enhancement. It's important to fill out the template properly before the matter is addressed. Please fill it out before we move forward. Provide the necessary details so we can consider assigning this issue.

**Comment by Mahak008** [comment]
> Hello @Mahak008. The issue template is provided to ensure we gather detailed information on the issue/proposed enhancement. It's important to fill out the template properly before the matter is addressed. Please fill it out before we move forward. Provide the necessary details so we can consider assigning this issue.

@ayushichoudhary-19 kindly check the issue. I have written all the changes that I would like to make.

**Comment by ayushichoudhary-19** [comment]
Fixed in #109
