### ISSUE TITLE
Change the background of portfolio.

### ISSUE THREAD

**Issue by Miss-Anisha** [SnowScriptWinterOfCode/PortfolioCreations#90]
### Issue Description

Background of the portfolio doesn't look very good. So, I would like to give it a gradient background.

### Expected Behavior

It will give a professional look.

### Additional Context

⚠️ **Warning**: Before submitting, please check for existing issues to avoid duplicates. If you find a related issue, consider adding your insights or upvoting the existing one. Thank you!

**Comment by Nitya-Pasrija** [comment]
Congratulations! Your first ever issue with us in this repository has been created. Please wait while it gets assigned to you.

**Comment by ayushichoudhary-19** [comment]
Hello @Miss-Anisha. The issue template is provided to ensure we gather detailed information on the issue. It's important to fill out the template properly before the matter is addressed. Please fill it out before we move forward. Provide the necessary details so we can consider assigning this issue.

**Comment by Miss-Anisha** [comment]
> Hello @Miss-Anisha. The issue template is provided to ensure we gather detailed information on the issue. It's important to fill out the template properly before the matter is addressed. Please fill it out before we move forward. Provide the necessary details so we can consider assigning this issue. 

I have given the complete description of the issue. Kindly review it.

**Comment by ayushichoudhary-19** [comment]
@Miss-Anisha Assigned. Submit a PR within 48 hours.
