### ISSUE TITLE
Change the animation of navbar.

### ISSUE THREAD

**Issue by Miss-Anisha** [SnowScriptWinterOfCode/PortfolioCreations#91]
### Issue Description

Change the animation of navbar because it does not look profressional.
### Additional Context

⚠️ **Warning**: Before submitting, please check for existing issues to avoid duplicates. If you find a related issue, consider adding your insights or upvoting the existing one. Thank you!

**Comment by ayushichoudhary-19** [comment]
Hi @Miss-Anisha. The issue template is there to help gather detailed information on the issue and is not supposed to be submitted as it is. However, in this submission, crucial details are missing, including a clear description of the issue and your ideas for changing the animation. As a result, I'm closing the issue as 'invalid' for now. Please consider reopening it with additional information. Your contributions are appreciated!
