### ISSUE TITLE
Add skills in the form of progress percentage.

### ISSUE THREAD

**Issue by Miss-Anisha** [SnowScriptWinterOfCode/PortfolioCreations#92]
### Additional Context

⚠️ **Warning**: Before submitting, please check for existing issues to avoid duplicates. If you find a related issue, consider adding your insights or upvoting the existing one. Thank you!

**Comment by ayushichoudhary-19** [comment]
@Miss-Anisha This is a duplicate issue, and another contributor is already working on it. If you have additional insights or details to add, feel free to contribute to the existing discussion. #7
