### ISSUE TITLE
[Feat]: ADD dark mode feature

### ISSUE THREAD

**Issue by bj-jiwrajka** [SnowScriptWinterOfCode/PortfolioCreations#95]
The website should also be available with dark mode

**Comment by bj-jiwrajka** [comment]
@ayushichoudhary-19 can I work on it?

**Comment by Nitya-Pasrija** [comment]
Congratulations! Your first ever issue with us in this repository has been created. Please wait while it gets assigned to you.

**Comment by ayushichoudhary-19** [comment]
@bj-jiwrajka, the issue is now assigned to you.

**Comment by ayushichoudhary-19** [comment]
@bj-jiwrajka What's the status of the pull request? Please submit it by midnight today, or else we'll have to open the issue for other contributors.

**Comment by hars-21** [comment]
Assign me Please
