### ISSUE TITLE
Home Page UI Enhancement

### ISSUE THREAD

**Issue by hars-21** [SnowScriptWinterOfCode/PortfolioCreations#99]
Front Home Page UI can be enhanced. Adding Background and Animation.

**Comment by hars-21** [comment]
Please assign this issue to me

**Comment by ayushichoudhary-19** [comment]
Sure, @Harshil-Gupta21. But before diving into implementation, let's have a quick discussion to ensure we're aligned on the design direction. Could you please share the proposed UI and animations? So that we can decide whether the additions align with the overall goals and aesthetics of our project.

**Comment by hars-21** [comment]
So this is the proposed UI. If you decide to add the corresponding animation then please assign me the issue as I am ready with my PR.
![Screen Shot 2024-01-09 at 6 54 45 PM](https://github.com/SnowScriptWinterOfCode/PortfolioCreations/assets/144909381/1355ca35-6259-41b8-a921-19e1de75ca31)
![Screen Shot 2024-01-09 at 6 54 48 PM](https://github.com/SnowScriptWinterOfCode/PortfolioCreations/assets/144909381/2486d73f-e72b-4c49-9c13-a2231522e6fe)

**Comment by hars-21** [comment]
@ayushichoudhary-19  Please tell is this UI approved, so that I can proceed further or are there any changes that have to be made?

**Comment by ayushichoudhary-19** [comment]
The color doesn't quite match the theme. We could try something else to better align with the look and feel.

**Comment by ayushichoudhary-19** [comment]
Additionally, please run `git pull` before making changes. In your last PR, you didn't work on the latest version of the repository.

**Comment by hars-21** [comment]
Ok I'll make the changes
